name: 'Compare Pypi and Poetry version'
description: 'Create outputs future steps can use depending if the pypi version is out of sync'
version: 1.0.0
inputs:
  package_name: 
    description: 'Name of pypi package'
    required: true
outputs:
  pypi_package_exists:
    description: "'true' or 'false' there is a pypi item for this repo"
    value: ${{ steps.get_version_status.outputs.pypi_package_exists }}
  pypi_version_difference:
    description: "'true' or 'false' if there is a difference between poetry and pypi version"
    value: ${{ steps.get_version_status.outputs.pypi_version_difference }}
  repo_poetry_version:
    description: "Current poetry semvar version"
    value: ${{ steps.get_version_status.outputs.repo_poetry_version }}
runs:
  using: "composite"
  steps:

    - uses: ajparsons/get-config-value@e360e43a7c254b56590f07c95ec8b810f8575ed6 # v1.0.0
      id: read_toml
      with:
        file: 'pyproject.toml'
        key: 'tool.poetry.version'

    - name: get_version_status
      id: get_version_status
      run: |
        ${{ github.action_path }}/get_version_status.sh
      shell: bash
      env:
        pythonPackage: ${{ inputs.package_name }}
        localVersion: ${{ steps.read_toml.outputs.value }}